### PR TITLE
Add support for redis connection url's

### PR DESCRIPTION
**Pull request by pthm**
Adds support for specifying a `url` property in options to use with `.createClient()`

As described here https://github.com/NodeRedis/node_redis#rediscreateclient

### CODE REVIEW

**Comment by mihaidma** [comment]
I noticed one more line where port and host are used: https://github.com/senecajs/seneca-redis-queue-transport/blob/master/redis-queue-transport.js#L108

The Travis failure seems to be caused by the decreasing test threshold. Is it possible to add more tests not to decrease the code coverage?

**Comment by pthm** [comment]
Fixed that issue with the host/port. Tried increasing test coverage but at a bit of a loose end as to how to test the Redis connection because its not exposed publicly. Exposing it would just require even more testing

**Comment by mcdonnelldean** [comment]
@pthm Could you resolve the conflict? There were a couple of changes needed to be made that are now in. Don't sweat the coverage if you have hit a wall there. Just update the conflicts and I can merge in.

**Comment by pthm** [comment]
Updated the conflicts, not sure what happening with GitHub though. There also appears to be another issue with the `happy-pin` test that exists in master too

**Comment by mihaidma** [comment]
i'll check this issue

**Comment by mihaidma** [comment]
it seems that the tests need reviewing/rewriting, this PR will take a while

**Pull request closed without merging**
