### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jreeter**
An attempt to provide better documentation.

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
(note: unrelated broken build since README modification.
after brie overlook of travis build: for some reason seneca Panics occurs.
My guess, is it might be induced by some dep evolution.
(Relaunched test to see if false alert (-> it's not)))

**Comment by jreeter** [comment]
@AdrieanKhisbe  anything I need to do to get this to pass CI?

**Comment by AdrieanKhisbe** [comment]
No idea =/
(And no time To dig right now)
Does the test pass on your machine?

**Comment by mcdonnelldean** [comment]
I think its a travis config issue @mihaidma can we get someone to look at this?

**Comment by mihaidma** [comment]
@mcdonnelldean ok

**Comment by ckiss** [comment]
I need to fix the tests and linting. I've opened an issue: https://github.com/senecajs/seneca-redis-queue-transport/issues/15

**Pull request merged**
